export const TYPES = {
  RESET: 'RESET',
  MARK_MATCH: 'MARK_MATCH',
  COUNTING: 'COUNTING',
  CHANGE_HIGHESTSPEED: 'CHANGE_HIGHESTSPEED',
  CHANGE_STATUS: 'CHANGE_STATUS',
  FLIP_CARD: 'FLIP_CARD',
  FLIP_CARDS: 'FLIP_CARDS'
}
